"""
TUPLE -- ORDERED , IMMUTABLE , INDEXED
TUPLE -- NO MODIFICATION ALLOWED
TUPLE -- NEGATIVE INDEXING POSSIBLE
TUPLE -- UPDATION NHI  HO SKTI

"""

# TUPLE OPERARIONS
"""
LEN()
COUNT()
CLEAR() MAY BE
SLICING
"""